theme: jekyll-theme-minimal
title: Jordan's Home Page
description: Hi, I am a Tech Lead with a strong focus on Microsoft technologies such as .NET, SharePoint, M365, and Azure.
github_username:  jordanlacroix
